### ISSUE TITLE
Check for dependency updates for existing projects

### ISSUE THREAD

**Issue by Skrilltrax** [msfjarvis/adx#41]
Add a command-line argument (something like --project) to check for updates available in an existing project. I think we can dump the results of `./gradlew dependecies` and then parse it to get the libraries. After that, we can just run it through the main adx flow to get the desired output.

## Expected Input  
```
adx --project /home/username/android-project
```

## Expected output  
```
androidx.appcompat:appcompat:1.2.0
androidx.appcompat:appcompat-resources:1.2.0
```

**Comment by msfjarvis** [comment]
We'll end up needing to build a parser with either [peg](https://lib.rs/crates/peg) or [nom](https://lib.rs/crates/nom) which can handle individual lines from the graph `./gradlew dependencies` generates but I'm inexperienced in that field so it'll take a bit of time and elbow grease.
